### ISSUE TITLE
hid for windows?

### ISSUE THREAD

**Issue by tigermendoza** [avilleret/hid#2]
Hi, 
I know the last update was a while back but as development on PD-Extended has stopped I'm trying to get hid to work with the latest windows version of PureData (Pure Data 0.49-0 for x64 at time of writing). Any advice on how I can get it installed and working?
Thanks!
Ian

**Comment by avilleret** [comment]
hi, unfortunately there is no binary on Deken for Windows
so you might have to build it yourself from source, or ask on the Pd-list if someone already have a working version for windows.
Btw, did you try to copy the hid.dll from Pd-extended ? It might work since API didn't change a lot

**Comment by tigermendoza** [comment]
Thanks for getting back to me. I did copy the hid.dll from Pd-extended but it won't work with the x64 windows binary however It does work with the x32 version so I'm using that instead :)
